name: build_node
on:
    workflow_call:
jobs:
    test:
        strategy:
            matrix:
                include:
                    - near_wallet_env: testnet_STAGING
                      test_dynamo_port: 8005
                    - near_wallet_env: testnet
                      test_dynamo_port: 8006
                    - near_wallet_env: mainnet_STAGING
                      test_dynamo_port: 8007
                    - near_wallet_env: mainnet
                      test_dynamo_port: 8008
            max-parallel: 2
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  cache: yarn
                  node-version: 12
            - run: yarn

            - name: environment tests
              run: NEAR_WALLET_ENV=${{ matrix.near_wallet_env }} TEST_DYNAMO_PORT=${{ matrix.test_dynamo_port }} yarn test
