name: deployment
on:
    pull_request:
        branches:
            - master
jobs:
    lint:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  cache: yarn
                  node-version: 12
            - run: yarn && yarn lint
    test:
        uses: ./.github/workflows/build_node.yml
